-- =============================================================================
-- Ventas nacionales de CAES (COOPERATIVE.features.ventaNacionalExportacion):
-- el papel real de CAES ("PACKING LIST-NACIONAL" CAESP-PP-BPM-RE-CPR-008 y
-- "Guía de Remisión Electrónica") confirma que una venta nacional NO usa
-- contenedor marítimo, booking, ni puerto de destino -- se despacha con una
-- Guía de Remisión (ya modelada en transporte_tramo1/2_guias, ver
-- 20260913250000). Pero el step "contenedor" (compartido con Norandino) hoy
-- exige container_number/container_size/booking_number/destination_port
-- como obligatorios -- eso bloquea guardar el registro para una orden
-- nacional antes de siquiera llegar a la pantalla de despacho.
--
-- Fila cooperativa-específica para CAES (misma herencia ya usada en
-- [[project_verificacion_limpieza_caes]]): mismos 22 campos que la fila
-- global (20260913250000), solo cambia required a false en esos 4 -- el
-- resto de la UI/validación no se toca. Norandino sigue usando la fila
-- global sin cambios (siempre exporta, esos 4 campos le siguen aplicando).
--
-- El INSERT vivía acá con el cooperative_id de CAES puesto a mano, pero las
-- migraciones corren TODAS antes que seed.sql (que es donde recién se crean
-- las cooperativas) -- en un "db reset" desde cero, esa tabla todavía está
-- vacía y el INSERT rompe con foreign key violation. Mismo bug ya corregido
-- antes (ver seed.sql, sección 5). La fila se movió a seed.sql, ya con el
-- campo "packing_list_numero" que la migración 20260913270000 le agregaba
-- después vía UPDATE (esa migración queda como no-op inofensivo en un reset
-- desde cero: no encuentra la fila porque seed.sql corre después, pero eso
-- no rompe nada -- el estado final ya sale completo desde seed.sql).
-- =============================================================================;
