-- =============================================================================
-- Verificación de Limpieza para CAES: catálogo de áreas/ítems propio.
--
-- La Verificación del Programa de Limpieza y Sanitización (SIG-GIA-RG-009
-- en Norandino) reusa el mismo motor para CAES (misma tabla
-- plant_cleaning_verification_controls, mismo VerificacionLimpiezaPage.jsx
-- -- por fecha, condición C/NC + acción correctiva) pero con un catálogo de
-- áreas/ítems propio, calcado del papel real de CAES "Inspección de
-- Ambientes, Equipos y Personal" (CAESP-PP-HYS-RE-HYS-002). Aprovecha la
-- herencia ya existente de form_configurations (cooperativa-específica >
-- global > default en código, ver lib/formConfig.js loadVerificacionLimpiezaAreas())
-- -- no hace falta ningún flag nuevo en COOPERATIVE.features ni cambios de
-- código: el DEFAULT en formConfig.js sigue siendo el de Norandino, y esta
-- fila cooperativa-específica lo reemplaza SOLO para CAES.
--
-- "OTROS (ESPECIFICAR)" del papel (filas en blanco para agregar libremente)
-- no se modela acá -- el campo "Observaciones" general del control cumple
-- ese rol; si hace falta más trazabilidad ahí, se puede sumar después.
--
-- El INSERT vivía acá con el cooperative_id de CAES puesto a mano, pero las
-- migraciones corren TODAS antes que seed.sql (que es donde recién se crean
-- las cooperativas) -- en un "db reset" desde cero, esa tabla todavía está
-- vacía y el INSERT rompe con foreign key violation. Mismo bug ya corregido
-- una vez antes (ver seed.sql, sección 5, "shelf_life_config"); se aplica el
-- mismo arreglo acá: la fila se movió a seed.sql, sección 5.
-- =============================================================================
